#!/bin/bash

sed -i "/DB_NAME/s/\"\([^\"]*\)\"/\"${DB_NAME}\"/2g" /var/www/html/config.php
sed -i "/DB_USER/s/\"\([^\"]*\)\"/\"${DB_USERNAME}\"/2g" /var/www/html/config.php
sed -i "/DB_PASS/s/\"\([^\"]*\)\"/\"${DB_PASSWORD}\"/2g" /var/www/html/config.php
sed -i "/DB_ADDR/s/\"\([^\"]*\)\"/\"${DB_HOST}\"/2g" /var/www/html/config.php

if [ "true" == "$UPDATE_DB" ]
then
    while ! mysqladmin ping --host="${DB_HOST}" --user="${DB_USERNAME}" --password="${DB_PASSWORD}" --silent; do
        echo 'Waiting for database to come up...'
        sleep 2
    done
    if [ $(mysql -N -s --host=${DB_HOST} --user=${DB_USER} --password=${DB_PASSWORD} -e \
        "select count(*) from information_schema.tables where \
            table_schema='${DB_NAME}' and table_name='hlstats_Servers';") -eq 1 ]; then
        echo 'Database is already filled'
    else
        echo 'Importing database tables'
        mysql --host=${DB_HOST} --user=${DB_USER} --password=${DB_PASSWORD} ${DB_NAME} < /var/www/html/sql/install.sql
    fi
    rm -R sql/
else
    rm -R updater/ sql/
fi

exec "docker-php-entrypoint" $@